ignore:
  - "**/*Adapter.*"
  - "**/*Activity.*"
  - "**/*Fragment.*"
  - "**/R.class"
  - "**/R$*.class"
  - "**/BuildConfig.*"
  - "**/Manifest*.*"
  - "android/**/*.*"
  - "**/*Test*.*"
  - "**/testing/**"
  - "**/di/**",
  - "**/*Dagger.*"
  - "**/architecture_testing/agent/*.*"
  - "hilt_*/***"
  - "**/databinding/**"