version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  unit-test:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/run-tests:
          test-command: ./gradlew check
      - android/save-gradle-cache
      - store_artifacts:
          path: test/results.xml
          destination: test
      - store_test_results:
          path: test
workflows:
  build-workflow:
    jobs:
      - unit-test