version: 2.1

orbs:
  android: circleci/android@2.1.2
  codecov: codecov/codecov@3.2.3

jobs:
  unit-test:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew jacocoTestReport
      - android/save-gradle-cache
      - codecov/upload
workflows:
  build-workflow:
    jobs:
      - unit-test