version: 2.1

orbs:
  android: circleci/android@2.1.2
  ruby: circleci/ruby@2.0.0

jobs:
  unit_test:
    executor:
      name: android/android-docker
      tag: 2022.09.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew testDebugUnitTest
      - android/save-gradle-cache
workflows:
  build-workflow:
    jobs:
      - unit_test