version: 2.1

orbs:
  android: circleci/android@2.1.2
  ruby: circleci/ruby@2.0.0

jobs:
  unit_test:
    executor:
      name: android/android-docker
      tag: 2022.09.1
    steps:
      - checkout

      - android/restore-gradle-cache

      - run: ./gradlew testDebugUnitTest

      - android/save-gradle-cache

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

            - store_test_results:
                path: ~/test-results

            - store_artifacts:
                path: ~/test-results/junit

workflows:
  main:
    jobs:
      - unit_test