version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  unit-test:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew test --no-daemon
      - android/save-gradle-cache
workflows:
  build-workflow:
    jobs:
      - unit-test