name: "Setup Android Build"
description: "Common steps before running a Gradle command"

runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v2.3.0
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.2.2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/development' }}

    - name: Optimize for Gradle build
      shell: bash
      run: |
        cp .github/ci-gradle.properties $GITHUB_WORKSPACE/gradle.properties
