name: Android CI

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: Setup Android Build
        uses: ./.github/actions/setup-android-build
        timeout-minutes: 5
      - name: Build with Gradle
        run: ./gradlew build

  test-unit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3

      - name: Setup Android Build
        uses: ./.github/actions/setup-android-build
        timeout-minutes: 5

      - name: Build with Gradle
        run: ./gradlew test