name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1.0.4
      - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: 11

      - name: Build project
        run: ./gradlew build

      - name: Check project
        run: ./gradlew check