name: verify-build

on:
  push:
    branches:
      - development

concurrency:
  # Cancels only outdated pull request runs; Run all builds on development
  # See https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - name: git clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 100 # Workaround to avoid https://github.com/danger/danger/issues/768
    - name: Setup Android Build
      uses: ./.github/actions/setup-android-build
      # This shouldn't take more than a minute, but it can get stuck if dependencies bug out
      # See https://github.com/actions/runner/issues/1979
      timeout-minutes: 5
    - name: Build with Gradle
      run: ./gradlew check